
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONFIGURATION=Realase
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=ToDoDb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:80
      - Kestrel__Endpoints__Http__Url=http://+:80
      - Kestrel__AllowAnyIP=true
      - CORS__AllowedOrigins=*
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ToDoDb
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: always

volumes:
  todo-mysql-data:
